[upstox]
api_key = "cfec43af-7298-4cc2-ae8d-af1339f14668"
api_secret = "oftgc7g0bx"
redirect_uri = "http://localhost"  # or your deployed app URL
access_token = "eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiI0SkFMNjMiLCJqdGkiOiI2OGE4ZDU5NWU4M2QxZDY4ZDk5YWU3MGYiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6ZmFsc2UsImlhdCI6MTc1NTg5NTE4OSwiaXNzIjoidWRhcGktZ2F0ZXdheS1zZXJ2aWNlIiwiZXhwIjoxNzU1OTAwMDAwfQ.nyLMGLh180NWBzrbiwnyPmh7o9FtCptLhxoBv3L8l5k"
